さて、うまくいくかな

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -16,8 +16,15 @@ jobs:
     # Error Check
     - name: Run install.sh
       run: ${GITHUB_WORKSPACE}/install.sh
-      
-    - name: Load .bashrc
+
+    - name: Check if .bashrc exists in repository
       run: |
-        bash ~/.bashrc 2> error.log; cat error.log
-        if [ -s error.log ]; then false; fi
+        # GitHub Actions のワークスペース内のパスを確認
+        HOME_PATH="~/.bashrc"
+
+        if [ -f "$HOME_PATH" ]; then
+          echo "::notice file=$HOME_PATH::.bashrc exists in the repository."
+        else
+          echo "::error file=$HOME_PATH::.bashrc does NOT exist in the repository!"
+          exit 1 # ファイルがない場合はステップを失敗させる
+        fi
